version: '3.8'

services:
  mysql:
    image: mysql:9.2.0
    container_name: performa-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: performa
      MYSQL_USER: performa
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
