from base.base_model import db
from models import User, Term, Program, Course, TermProgramCourse, Enrollment, Grade
from models import UserRole

from models.grade.attendance import Attendance
from models.grade.students_archive import StudentsArchive
from models.grade.students_grades_archive import StudentsGradesArchive

def init_database(_app):
    with _app.app_context():
        db.drop_all()
        db.create_all()
        UserRole.save_all(
            UserRole(id=1, name="STUDENT"),
            UserRole(id=2, name="INSTRUCTOR"),
            UserRole(id=3, name="ADMIN"),
        )

        User.save_all(
            User(id=1, email="admin@conestogac.on.ca", first_name="Admin", last_name="", role_id=3),
            User(id=2, email="cc@conestogac.on.ca", first_name="Ce", last_name="Chen", role_id=1),
            User(id=3, email="mila@conestogac.on.ca", first_name="Mila", last_name="Yang", role_id=1),
            User(id=4, email="bin@conestogac.on.ca", first_name="Bin", last_name="Hu", role_id=1),
            User(id=5, email="anuroopa@conestogac.on.ca", first_name="Anuroopa", last_name="Balachandran", role_id=1),
            User(id=6, email="alex@conestogac.on.ca", first_name="Alex", last_name="", role_id=2),
            User(id=7, email="eric@conestogac.on.ca", first_name="Eric", last_name="", role_id=2),
            User(id=8, email="jomis@conestogac.on.ca", first_name="Jomis", last_name="", role_id=2),
            User(id=9, email="amrita@conestogac.on.ca", first_name="Amrita", last_name="", role_id=2),
            User(id=10, email="ahmed@conestogac.on.ca", first_name="Ahmed", last_name="", role_id=2),
            User(id=11, email="user11@conestogac.on.ca", first_name="John", last_name="Doe", role_id=1),
            User(id=12, email="user12@conestogac.on.ca", first_name="Jane", last_name="Smith", role_id=1),
            User(id=13, email="user13@conestogac.on.ca", first_name="Michael", last_name="Brown", role_id=1),
            User(id=14, email="user14@conestogac.on.ca", first_name="Emily", last_name="Davis", role_id=1),
            User(id=15, email="user15@conestogac.on.ca", first_name="David", last_name="Wilson", role_id=1),
            User(id=16, email="user16@conestogac.on.ca", first_name="Sarah", last_name="Johnson", role_id=1),
            User(id=17, email="user17@conestogac.on.ca", first_name="Daniel", last_name="Martinez", role_id=1),
            User(id=18, email="user18@conestogac.on.ca", first_name="Laura", last_name="Taylor", role_id=1),
            User(id=19, email="user19@conestogac.on.ca", first_name="James", last_name="Anderson", role_id=1),
            User(id=20, email="user20@conestogac.on.ca", first_name="Olivia", last_name="Thomas", role_id=1),
            User(id=21, email="user21@conestogac.on.ca", first_name="Robert", last_name="Hernandez", role_id=1),
            User(id=22, email="user22@conestogac.on.ca", first_name="Emma", last_name="Moore", role_id=1),
            User(id=23, email="user23@conestogac.on.ca", first_name="William", last_name="Jackson", role_id=1),
            User(id=24, email="user24@conestogac.on.ca", first_name="Sophia", last_name="White", role_id=1),
            User(id=25, email="user25@conestogac.on.ca", first_name="Ethan", last_name="Harris", role_id=1),
            User(id=26, email="user26@conestogac.on.ca", first_name="Mia", last_name="Clark", role_id=1),
            User(id=27, email="user27@conestogac.on.ca", first_name="Alexander", last_name="Rodriguez", role_id=1),
            User(id=28, email="user28@conestogac.on.ca", first_name="Charlotte", last_name="Lewis", role_id=1),
            User(id=29, email="user29@conestogac.on.ca", first_name="Benjamin", last_name="Walker", role_id=1),
            User(id=30, email="user30@conestogac.on.ca", first_name="Amelia", last_name="Hall", role_id=1),
        )

        Term.save_all(
            Term(id=1, year=2025, season="Winter", section=1, start_date='2025-01-01', end_date='2025-04-30'),
            Term(id=2, year=2024, season="Fall", section=1, start_date="2024-09-01", end_date="2024-12-31"),
            Term(id=3, year=2024, season="Spring", section=1, start_date="2024-05-01", end_date="2024-08-31"),
            Term(id=4, year=2024, season="Winter", section=1, start_date="2024-01-01", end_date="2024-04-30"),
        )

        Program.save_all(
            Program(id=1, code="1448", name="Big Data Solution Architecture", co_op=True)
        )

        Course.save_all(
            Course(id=1, code="PROG8401", name="Relational Database Design"),
            Course(id=2, code="PROG8411", name="NoSQL Database Implementation"),
            Course(id=3, code="PROG8421", name="Programming for Big Data"),
            Course(id=4, code="PROG8441", name="Software Quality"),
            Course(id=5, code="PROG8461", name="Web Analytics and Business Intelligence Tools"),
            Course(id=6, code="ETHS8011", name="Ethics and Security"),
            Course(id=7, code="INFO8121", name="Emerging Trends in Big Data"),
            Course(id=8, code="PROG8435", name="Data Analysis Mathematics, Algorithms and Modeling"),
            Course(id=9, code="PROG8451", name="Big Data Integration and Storage"),
            Course(id=10, code="SENG8081", name="Case Studies")
        )

        TermProgramCourse.save_all(
            TermProgramCourse(id=1, term_id=1, program_id=1, course_id=1, instructor_id=6, credits=6, program_level=1),
            TermProgramCourse(id=2, term_id=1, program_id=1, course_id=2, instructor_id=7, credits=3, program_level=1),
            TermProgramCourse(id=3, term_id=1, program_id=1, course_id=3, instructor_id=8, credits=6, program_level=1),
            TermProgramCourse(id=4, term_id=1, program_id=1, course_id=4, instructor_id=9, credits=3, program_level=1),
            TermProgramCourse(id=5, term_id=1, program_id=1, course_id=5, instructor_id=10, credits=4, program_level=1),
            TermProgramCourse(id=6, term_id=1, program_id=1, course_id=6, instructor_id=6, credits=3, program_level=2),
            TermProgramCourse(id=7, term_id=1, program_id=1, course_id=7, instructor_id=7, credits=3, program_level=2),
            TermProgramCourse(id=8, term_id=1, program_id=1, course_id=8, instructor_id=8, credits=6, program_level=2),
            TermProgramCourse(id=9, term_id=1, program_id=1, course_id=9, instructor_id=9, credits=6, program_level=2),
            TermProgramCourse(id=10, term_id=1, program_id=1, course_id=10, instructor_id=10, credits=5,
                              program_level=2),
            TermProgramCourse(id=11, term_id=2, program_id=1, course_id=1, instructor_id=6, credits=6, program_level=1),
            TermProgramCourse(id=12, term_id=2, program_id=1, course_id=2, instructor_id=7, credits=3, program_level=1),
            TermProgramCourse(id=13, term_id=2, program_id=1, course_id=3, instructor_id=8, credits=6, program_level=1),
            TermProgramCourse(id=14, term_id=2, program_id=1, course_id=4, instructor_id=9, credits=3, program_level=1),
            TermProgramCourse(id=15, term_id=2, program_id=1, course_id=5, instructor_id=10, credits=4,
                              program_level=1),
            TermProgramCourse(id=16, term_id=2, program_id=1, course_id=6, instructor_id=6, credits=3, program_level=2),
            TermProgramCourse(id=17, term_id=2, program_id=1, course_id=7, instructor_id=7, credits=3, program_level=2),
            TermProgramCourse(id=18, term_id=2, program_id=1, course_id=8, instructor_id=8, credits=6, program_level=2),
            TermProgramCourse(id=19, term_id=2, program_id=1, course_id=9, instructor_id=9, credits=6, program_level=2),
            TermProgramCourse(id=20, term_id=2, program_id=1, course_id=10, instructor_id=10, credits=5,
                              program_level=2),
            TermProgramCourse(id=21, term_id=3, program_id=1, course_id=1, instructor_id=6, credits=6, program_level=1),
            TermProgramCourse(id=22, term_id=3, program_id=1, course_id=2, instructor_id=7, credits=3, program_level=1),
            TermProgramCourse(id=23, term_id=3, program_id=1, course_id=3, instructor_id=8, credits=6, program_level=1),
            TermProgramCourse(id=24, term_id=3, program_id=1, course_id=4, instructor_id=9, credits=3, program_level=1),
            TermProgramCourse(id=25, term_id=3, program_id=1, course_id=5, instructor_id=10, credits=4,
                              program_level=1),
            TermProgramCourse(id=26, term_id=3, program_id=1, course_id=6, instructor_id=6, credits=3, program_level=2),
            TermProgramCourse(id=27, term_id=3, program_id=1, course_id=7, instructor_id=7, credits=3, program_level=2),
            TermProgramCourse(id=28, term_id=3, program_id=1, course_id=8, instructor_id=8, credits=6, program_level=2),
            TermProgramCourse(id=29, term_id=3, program_id=1, course_id=9, instructor_id=9, credits=6, program_level=2),
            TermProgramCourse(id=30, term_id=3, program_id=1, course_id=10, instructor_id=10, credits=5,
                              program_level=2),
            TermProgramCourse(id=31, term_id=4, program_id=1, course_id=1, instructor_id=6, credits=6, program_level=1),
            TermProgramCourse(id=32, term_id=4, program_id=1, course_id=2, instructor_id=7, credits=3, program_level=1),
            TermProgramCourse(id=33, term_id=4, program_id=1, course_id=3, instructor_id=8, credits=6, program_level=1),
            TermProgramCourse(id=34, term_id=4, program_id=1, course_id=4, instructor_id=9, credits=3, program_level=1),
            TermProgramCourse(id=35, term_id=4, program_id=1, course_id=5, instructor_id=10, credits=4,
                              program_level=1),
            TermProgramCourse(id=36, term_id=4, program_id=1, course_id=6, instructor_id=6, credits=3, program_level=2),
            TermProgramCourse(id=37, term_id=4, program_id=1, course_id=7, instructor_id=7, credits=3, program_level=2),
            TermProgramCourse(id=38, term_id=4, program_id=1, course_id=8, instructor_id=8, credits=6, program_level=2),
            TermProgramCourse(id=39, term_id=4, program_id=1, course_id=9, instructor_id=9, credits=6, program_level=2),
            TermProgramCourse(id=40, term_id=4, program_id=1, course_id=10, instructor_id=10, credits=5,
                              program_level=2)
        )

        Enrollment.save_all(
            Enrollment(student_id=2, term_id=1, program_id=1),
            Enrollment(student_id=3, term_id=1, program_id=1),
            Enrollment(student_id=4, term_id=1, program_id=1),
            Enrollment(student_id=5, term_id=1, program_id=1),
            Enrollment(student_id=11, term_id=1, program_id=1),
            Enrollment(student_id=12, term_id=1, program_id=1),
            Enrollment(student_id=13, term_id=1, program_id=1),
            Enrollment(student_id=14, term_id=1, program_id=1),
            Enrollment(student_id=15, term_id=1, program_id=1),
            Enrollment(student_id=16, term_id=1, program_id=1),
            Enrollment(student_id=17, term_id=1, program_id=1),
            Enrollment(student_id=18, term_id=1, program_id=1),
            Enrollment(student_id=19, term_id=1, program_id=1),
            Enrollment(student_id=20, term_id=1, program_id=1),
            Enrollment(student_id=21, term_id=1, program_id=1),
            Enrollment(student_id=22, term_id=1, program_id=1),
            Enrollment(student_id=23, term_id=1, program_id=1),
            Enrollment(student_id=24, term_id=1, program_id=1),
            Enrollment(student_id=25, term_id=1, program_id=1),
            Enrollment(student_id=26, term_id=1, program_id=1),
            Enrollment(student_id=27, term_id=1, program_id=1),
            Enrollment(student_id=28, term_id=1, program_id=1),
            Enrollment(student_id=29, term_id=1, program_id=1),
            Enrollment(student_id=30, term_id=1, program_id=1),
        )

        Grade.save_all(
            Grade(student_id=2, tp_course_id=1, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=2, tp_course_id=2, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=2, tp_course_id=3, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=2, tp_course_id=4, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=2, tp_course_id=5, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=3, tp_course_id=1, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=3, tp_course_id=2, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=3, tp_course_id=3, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=3, tp_course_id=4, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=3, tp_course_id=5, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=4, tp_course_id=1, final_grade=20.0, final_gpa=0.0),
            Grade(student_id=4, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=4, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=4, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=4, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=5, tp_course_id=1, final_grade=40.0, final_gpa=0.0),
            Grade(student_id=5, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=5, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=5, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=5, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=11, tp_course_id=1, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=11, tp_course_id=2, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=11, tp_course_id=3, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=11, tp_course_id=4, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=11, tp_course_id=5, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=12, tp_course_id=1, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=12, tp_course_id=2, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=12, tp_course_id=3, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=12, tp_course_id=4, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=12, tp_course_id=5, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=13, tp_course_id=1, final_grade=20.0, final_gpa=0.0),
            Grade(student_id=13, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=13, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=13, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=13, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=14, tp_course_id=1, final_grade=40.0, final_gpa=0.0),
            Grade(student_id=14, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=14, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=14, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=14, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=15, tp_course_id=1, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=15, tp_course_id=2, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=15, tp_course_id=3, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=15, tp_course_id=4, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=15, tp_course_id=5, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=16, tp_course_id=1, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=16, tp_course_id=2, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=16, tp_course_id=3, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=16, tp_course_id=4, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=16, tp_course_id=5, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=17, tp_course_id=1, final_grade=20.0, final_gpa=0.0),
            Grade(student_id=17, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=17, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=17, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=17, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=18, tp_course_id=1, final_grade=40.0, final_gpa=0.0),
            Grade(student_id=18, tp_course_id=2, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=18, tp_course_id=3, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=18, tp_course_id=4, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=18, tp_course_id=5, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=19, tp_course_id=1, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=19, tp_course_id=2, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=19, tp_course_id=3, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=19, tp_course_id=4, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=19, tp_course_id=5, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=20, tp_course_id=1, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=20, tp_course_id=2, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=20, tp_course_id=3, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=20, tp_course_id=4, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=20, tp_course_id=5, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=6, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=7, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=8, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=9, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=10, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=22, tp_course_id=6, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=22, tp_course_id=7, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=22, tp_course_id=8, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=22, tp_course_id=9, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=22, tp_course_id=10, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=23, tp_course_id=6, final_grade=20.0, final_gpa=0.0),
            Grade(student_id=23, tp_course_id=7, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=23, tp_course_id=8, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=23, tp_course_id=9, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=23, tp_course_id=10, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=24, tp_course_id=6, final_grade=40.0, final_gpa=0.0),
            Grade(student_id=24, tp_course_id=7, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=24, tp_course_id=8, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=24, tp_course_id=9, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=24, tp_course_id=10, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=25, tp_course_id=6, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=25, tp_course_id=7, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=25, tp_course_id=8, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=25, tp_course_id=9, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=25, tp_course_id=10, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=26, tp_course_id=6, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=26, tp_course_id=7, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=26, tp_course_id=8, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=26, tp_course_id=9, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=26, tp_course_id=10, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=27, tp_course_id=6, final_grade=20.0, final_gpa=0.0),
            Grade(student_id=27, tp_course_id=7, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=27, tp_course_id=8, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=27, tp_course_id=9, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=27, tp_course_id=10, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=28, tp_course_id=6, final_grade=40.0, final_gpa=0.0),
            Grade(student_id=28, tp_course_id=7, final_grade=21.0, final_gpa=0.0),
            Grade(student_id=28, tp_course_id=8, final_grade=22.0, final_gpa=0.0),
            Grade(student_id=28, tp_course_id=9, final_grade=23.0, final_gpa=0.0),
            Grade(student_id=28, tp_course_id=10, final_grade=24.0, final_gpa=0.0),
            Grade(student_id=29, tp_course_id=6, final_grade=10.0, final_gpa=0.0),
            Grade(student_id=29, tp_course_id=7, final_grade=11.0, final_gpa=0.0),
            Grade(student_id=29, tp_course_id=8, final_grade=12.0, final_gpa=0.0),
            Grade(student_id=29, tp_course_id=9, final_grade=13.0, final_gpa=0.0),
            Grade(student_id=29, tp_course_id=10, final_grade=14.0, final_gpa=0.0),
            Grade(student_id=30, tp_course_id=6, final_grade=30.0, final_gpa=0.0),
            Grade(student_id=30, tp_course_id=7, final_grade=31.0, final_gpa=0.0),
            Grade(student_id=30, tp_course_id=8, final_grade=32.0, final_gpa=0.0),
            Grade(student_id=30, tp_course_id=9, final_grade=33.0, final_gpa=0.0),
            Grade(student_id=30, tp_course_id=10, final_grade=34.0, final_gpa=0.0),
            Grade(student_id=21, tp_course_id=11, final_grade=82.0, final_gpa=3.25),
            Grade(student_id=21, tp_course_id=12, final_grade=70.5, final_gpa=3.00),
            Grade(student_id=21, tp_course_id=13, final_grade=90.0, final_gpa=3.75),
            Grade(student_id=21, tp_course_id=14, final_grade=77.2, final_gpa=3.10),
            Grade(student_id=21, tp_course_id=15, final_grade=88.5, final_gpa=3.60),
            Grade(student_id=22, tp_course_id=11, final_grade=74.3, final_gpa=3.20),
            Grade(student_id=22, tp_course_id=12, final_grade=89.5, final_gpa=3.70),
            Grade(student_id=22, tp_course_id=13, final_grade=72.6, final_gpa=3.05),
            Grade(student_id=22, tp_course_id=14, final_grade=91.8, final_gpa=3.80),
            Grade(student_id=22, tp_course_id=15, final_grade=84.1, final_gpa=3.45),
            Grade(student_id=23, tp_course_id=11, final_grade=66.9, final_gpa=2.90),
            Grade(student_id=23, tp_course_id=12, final_grade=95.4, final_gpa=3.90),
            Grade(student_id=23, tp_course_id=13, final_grade=78.7, final_gpa=3.25),
            Grade(student_id=23, tp_course_id=14, final_grade=84.3, final_gpa=3.50),
            Grade(student_id=23, tp_course_id=15, final_grade=80.0, final_gpa=3.35),
            Grade(student_id=24, tp_course_id=11, final_grade=68.2, final_gpa=3.00),
            Grade(student_id=24, tp_course_id=12, final_grade=83.9, final_gpa=3.40),
            Grade(student_id=24, tp_course_id=13, final_grade=92.7, final_gpa=3.85),
            Grade(student_id=24, tp_course_id=14, final_grade=75.4, final_gpa=3.15),
            Grade(student_id=24, tp_course_id=15, final_grade=79.8, final_gpa=3.30),
            Grade(student_id=25, tp_course_id=11, final_grade=87.6, final_gpa=3.55),
            Grade(student_id=25, tp_course_id=12, final_grade=72.8, final_gpa=3.10),
            Grade(student_id=25, tp_course_id=13, final_grade=66.5, final_gpa=2.95),
            Grade(student_id=25, tp_course_id=14, final_grade=94.2, final_gpa=3.85),
            Grade(student_id=25, tp_course_id=15, final_grade=82.4, final_gpa=3.25),
            Grade(student_id=26, tp_course_id=11, final_grade=76.1, final_gpa=3.20),
            Grade(student_id=26, tp_course_id=12, final_grade=97.3, final_gpa=3.95),
            Grade(student_id=26, tp_course_id=13, final_grade=74.0, final_gpa=3.15),
            Grade(student_id=26, tp_course_id=14, final_grade=69.3, final_gpa=3.00),
            Grade(student_id=26, tp_course_id=15, final_grade=90.8, final_gpa=3.75),
            Grade(student_id=27, tp_course_id=11, final_grade=78.2, final_gpa=3.30),
            Grade(student_id=27, tp_course_id=12, final_grade=81.4, final_gpa=3.45),
            Grade(student_id=27, tp_course_id=13, final_grade=95.0, final_gpa=3.85),
            Grade(student_id=27, tp_course_id=14, final_grade=66.8, final_gpa=3.05),
            Grade(student_id=27, tp_course_id=15, final_grade=84.9, final_gpa=3.50),
            Grade(student_id=28, tp_course_id=11, final_grade=88.3, final_gpa=3.60),
            Grade(student_id=28, tp_course_id=12, final_grade=79.7, final_gpa=3.25),
            Grade(student_id=28, tp_course_id=13, final_grade=71.5, final_gpa=3.05),
            Grade(student_id=28, tp_course_id=14, final_grade=97.0, final_gpa=3.90),
            Grade(student_id=28, tp_course_id=15, final_grade=85.6, final_gpa=3.45),
            Grade(student_id=29, tp_course_id=11, final_grade=81.2, final_gpa=3.40),
            Grade(student_id=29, tp_course_id=12, final_grade=93.6, final_gpa=3.80),
            Grade(student_id=29, tp_course_id=13, final_grade=68.4, final_gpa=3.00),
            Grade(student_id=29, tp_course_id=14, final_grade=77.9, final_gpa=3.15),
            Grade(student_id=29, tp_course_id=15, final_grade=90.2, final_gpa=3.75),
            Grade(student_id=30, tp_course_id=11, final_grade=79.0, final_gpa=3.25),
            Grade(student_id=30, tp_course_id=12, final_grade=66.7, final_gpa=2.95),
            Grade(student_id=30, tp_course_id=13, final_grade=85.1, final_gpa=3.50),
            Grade(student_id=30, tp_course_id=14, final_grade=88.8, final_gpa=3.60),
            Grade(student_id=30, tp_course_id=15, final_grade=73.3, final_gpa=3.10),
        )

        Attendance.save_all(
            Attendance(student_id=2, tp_course_id=1, attendance_in_percent=92.0),
            Attendance(student_id=2, tp_course_id=2, attendance_in_percent=88.0),
            Attendance(student_id=2, tp_course_id=3, attendance_in_percent=85.0),
            Attendance(student_id=2, tp_course_id=4, attendance_in_percent=91.0),
            Attendance(student_id=2, tp_course_id=5, attendance_in_percent=87.0),
            Attendance(student_id=3, tp_course_id=1, attendance_in_percent=95.0),
            Attendance(student_id=3, tp_course_id=2, attendance_in_percent=93.0),
            Attendance(student_id=3, tp_course_id=3, attendance_in_percent=92.0),
            Attendance(student_id=3, tp_course_id=4, attendance_in_percent=96.0),
            Attendance(student_id=3, tp_course_id=5, attendance_in_percent=97.0),
            Attendance(student_id=4, tp_course_id=1, attendance_in_percent=90.0),
            Attendance(student_id=4, tp_course_id=2, attendance_in_percent=91.0),
            Attendance(student_id=4, tp_course_id=3, attendance_in_percent=92.0),
            Attendance(student_id=4, tp_course_id=4, attendance_in_percent=94.0),
            Attendance(student_id=4, tp_course_id=5, attendance_in_percent=88.0),
            Attendance(student_id=5, tp_course_id=1, attendance_in_percent=85.0),
            Attendance(student_id=5, tp_course_id=2, attendance_in_percent=80.0),
            Attendance(student_id=5, tp_course_id=3, attendance_in_percent=86.0),
            Attendance(student_id=5, tp_course_id=4, attendance_in_percent=84.0),
            Attendance(student_id=5, tp_course_id=5, attendance_in_percent=90.0),
            Attendance(student_id=11, tp_course_id=1, attendance_in_percent=81.0),
            Attendance(student_id=11, tp_course_id=2, attendance_in_percent=92.0),
            Attendance(student_id=11, tp_course_id=3, attendance_in_percent=85.0),
            Attendance(student_id=11, tp_course_id=4, attendance_in_percent=88.0),
            Attendance(student_id=11, tp_course_id=5, attendance_in_percent=89.0),
            Attendance(student_id=12, tp_course_id=1, attendance_in_percent=93.0),
            Attendance(student_id=12, tp_course_id=2, attendance_in_percent=96.0),
            Attendance(student_id=12, tp_course_id=3, attendance_in_percent=90.0),
            Attendance(student_id=12, tp_course_id=4, attendance_in_percent=92.0),
            Attendance(student_id=12, tp_course_id=5, attendance_in_percent=94.0),
            Attendance(student_id=13, tp_course_id=1, attendance_in_percent=91.0),
            Attendance(student_id=13, tp_course_id=2, attendance_in_percent=85.0),
            Attendance(student_id=13, tp_course_id=3, attendance_in_percent=80.0),
            Attendance(student_id=13, tp_course_id=4, attendance_in_percent=84.0),
            Attendance(student_id=13, tp_course_id=5, attendance_in_percent=93.0),
            Attendance(student_id=14, tp_course_id=1, attendance_in_percent=92.0),
            Attendance(student_id=14, tp_course_id=2, attendance_in_percent=88.0),
            Attendance(student_id=14, tp_course_id=3, attendance_in_percent=87.0),
            Attendance(student_id=14, tp_course_id=4, attendance_in_percent=94.0),
            Attendance(student_id=14, tp_course_id=5, attendance_in_percent=95.0),
            Attendance(student_id=15, tp_course_id=1, attendance_in_percent=81.0),
            Attendance(student_id=15, tp_course_id=2, attendance_in_percent=89.0),
            Attendance(student_id=15, tp_course_id=3, attendance_in_percent=92.0),
            Attendance(student_id=15, tp_course_id=4, attendance_in_percent=96.0),
            Attendance(student_id=15, tp_course_id=5, attendance_in_percent=85.0),
            Attendance(student_id=16, tp_course_id=1, attendance_in_percent=90.0),
            Attendance(student_id=16, tp_course_id=2, attendance_in_percent=88.0),
            Attendance(student_id=16, tp_course_id=3, attendance_in_percent=85.0),
            Attendance(student_id=16, tp_course_id=4, attendance_in_percent=91.0),
            Attendance(student_id=16, tp_course_id=5, attendance_in_percent=84.0),
            Attendance(student_id=17, tp_course_id=1, attendance_in_percent=95.0),
            Attendance(student_id=17, tp_course_id=2, attendance_in_percent=93.0),
            Attendance(student_id=17, tp_course_id=3, attendance_in_percent=92.0),
            Attendance(student_id=17, tp_course_id=4, attendance_in_percent=87.0),
            Attendance(student_id=17, tp_course_id=5, attendance_in_percent=96.0),
            Attendance(student_id=18, tp_course_id=1, attendance_in_percent=85.0),
            Attendance(student_id=18, tp_course_id=2, attendance_in_percent=80.0),
            Attendance(student_id=18, tp_course_id=3, attendance_in_percent=82.0),
            Attendance(student_id=18, tp_course_id=4, attendance_in_percent=84.0),
            Attendance(student_id=18, tp_course_id=5, attendance_in_percent=86.0),
            Attendance(student_id=19, tp_course_id=1, attendance_in_percent=90.0),
            Attendance(student_id=19, tp_course_id=2, attendance_in_percent=88.0),
            Attendance(student_id=19, tp_course_id=3, attendance_in_percent=91.0),
            Attendance(student_id=19, tp_course_id=4, attendance_in_percent=93.0),
            Attendance(student_id=19, tp_course_id=5, attendance_in_percent=89.0),
            Attendance(student_id=20, tp_course_id=1, attendance_in_percent=95.0),
            Attendance(student_id=20, tp_course_id=2, attendance_in_percent=92.0),
            Attendance(student_id=20, tp_course_id=3, attendance_in_percent=94.0),
            Attendance(student_id=20, tp_course_id=4, attendance_in_percent=96.0),
            Attendance(student_id=20, tp_course_id=5, attendance_in_percent=87.0),
            Attendance(student_id=21, tp_course_id=6, attendance_in_percent=89.0),
            Attendance(student_id=21, tp_course_id=7, attendance_in_percent=91.0),
            Attendance(student_id=21, tp_course_id=8, attendance_in_percent=94.0),
            Attendance(student_id=21, tp_course_id=9, attendance_in_percent=90.0),
            Attendance(student_id=21, tp_course_id=10, attendance_in_percent=92.0),
            Attendance(student_id=22, tp_course_id=6, attendance_in_percent=96.0),
            Attendance(student_id=22, tp_course_id=7, attendance_in_percent=92.0),
            Attendance(student_id=22, tp_course_id=8, attendance_in_percent=93.0),
            Attendance(student_id=22, tp_course_id=9, attendance_in_percent=95.0),
            Attendance(student_id=22, tp_course_id=10, attendance_in_percent=89.0),
            Attendance(student_id=23, tp_course_id=6, attendance_in_percent=91.0),
            Attendance(student_id=23, tp_course_id=7, attendance_in_percent=80.0),
            Attendance(student_id=23, tp_course_id=8, attendance_in_percent=90.0),
            Attendance(student_id=23, tp_course_id=9, attendance_in_percent=92.0),
            Attendance(student_id=23, tp_course_id=10, attendance_in_percent=85.0),
            Attendance(student_id=24, tp_course_id=6, attendance_in_percent=82.0),
            Attendance(student_id=24, tp_course_id=7, attendance_in_percent=94.0),
            Attendance(student_id=24, tp_course_id=8, attendance_in_percent=90.0),
            Attendance(student_id=24, tp_course_id=9, attendance_in_percent=89.0),
            Attendance(student_id=24, tp_course_id=10, attendance_in_percent=96.0),
            Attendance(student_id=25, tp_course_id=6, attendance_in_percent=84.0),
            Attendance(student_id=25, tp_course_id=7, attendance_in_percent=91.0),
            Attendance(student_id=25, tp_course_id=8, attendance_in_percent=82.0),
            Attendance(student_id=25, tp_course_id=9, attendance_in_percent=85.0),
            Attendance(student_id=25, tp_course_id=10, attendance_in_percent=93.0),
            Attendance(student_id=26, tp_course_id=6, attendance_in_percent=80.0),
            Attendance(student_id=26, tp_course_id=7, attendance_in_percent=86.0),
            Attendance(student_id=26, tp_course_id=8, attendance_in_percent=88.0),
            Attendance(student_id=26, tp_course_id=9, attendance_in_percent=94.0),
            Attendance(student_id=26, tp_course_id=10, attendance_in_percent=92.0),
            Attendance(student_id=27, tp_course_id=6, attendance_in_percent=93.0),
            Attendance(student_id=27, tp_course_id=7, attendance_in_percent=95.0),
            Attendance(student_id=27, tp_course_id=8, attendance_in_percent=87.0),
            Attendance(student_id=27, tp_course_id=9, attendance_in_percent=91.0),
            Attendance(student_id=27, tp_course_id=10, attendance_in_percent=92.0),
            Attendance(student_id=28, tp_course_id=6, attendance_in_percent=80.0),
            Attendance(student_id=28, tp_course_id=7, attendance_in_percent=82.0),
            Attendance(student_id=28, tp_course_id=8, attendance_in_percent=88.0),
            Attendance(student_id=28, tp_course_id=9, attendance_in_percent=85.0),
            Attendance(student_id=28, tp_course_id=10, attendance_in_percent=90.0),
            Attendance(student_id=29, tp_course_id=6, attendance_in_percent=95.0),
            Attendance(student_id=29, tp_course_id=7, attendance_in_percent=90.0),
            Attendance(student_id=29, tp_course_id=8, attendance_in_percent=93.0),
            Attendance(student_id=29, tp_course_id=9, attendance_in_percent=87.0),
            Attendance(student_id=29, tp_course_id=10, attendance_in_percent=84.0),
            Attendance(student_id=30, tp_course_id=6, attendance_in_percent=81.0),
            Attendance(student_id=30, tp_course_id=7, attendance_in_percent=92.0),
            Attendance(student_id=30, tp_course_id=8, attendance_in_percent=88.0),
            Attendance(student_id=30, tp_course_id=9, attendance_in_percent=93.0),
            Attendance(student_id=30, tp_course_id=10, attendance_in_percent=91.0),
            Attendance(student_id=21, tp_course_id=11, attendance_in_percent=89.0),
            Attendance(student_id=21, tp_course_id=12, attendance_in_percent=94.0),
            Attendance(student_id=21, tp_course_id=13, attendance_in_percent=93.0),
            Attendance(student_id=21, tp_course_id=14, attendance_in_percent=95.0),
            Attendance(student_id=21, tp_course_id=15, attendance_in_percent=90.0),
            Attendance(student_id=22, tp_course_id=11, attendance_in_percent=91.0),
            Attendance(student_id=22, tp_course_id=12, attendance_in_percent=80.0),
            Attendance(student_id=22, tp_course_id=13, attendance_in_percent=84.0),
            Attendance(student_id=22, tp_course_id=14, attendance_in_percent=92.0),
            Attendance(student_id=22, tp_course_id=15, attendance_in_percent=88.0),
            Attendance(student_id=23, tp_course_id=11, attendance_in_percent=81.0),
            Attendance(student_id=23, tp_course_id=12, attendance_in_percent=89.0),
            Attendance(student_id=23, tp_course_id=13, attendance_in_percent=93.0),
            Attendance(student_id=23, tp_course_id=14, attendance_in_percent=92.0),
            Attendance(student_id=23, tp_course_id=15, attendance_in_percent=95.0),
            Attendance(student_id=24, tp_course_id=11, attendance_in_percent=94.0),
            Attendance(student_id=24, tp_course_id=12, attendance_in_percent=81.0),
            Attendance(student_id=24, tp_course_id=13, attendance_in_percent=90.0),
            Attendance(student_id=24, tp_course_id=14, attendance_in_percent=92.0),
            Attendance(student_id=24, tp_course_id=15, attendance_in_percent=91.0),
            Attendance(student_id=25, tp_course_id=11, attendance_in_percent=80.0),
            Attendance(student_id=25, tp_course_id=12, attendance_in_percent=91.0),
            Attendance(student_id=25, tp_course_id=13, attendance_in_percent=88.0),
            Attendance(student_id=25, tp_course_id=14, attendance_in_percent=95.0),
            Attendance(student_id=25, tp_course_id=15, attendance_in_percent=84.0),
            Attendance(student_id=26, tp_course_id=11, attendance_in_percent=85.0),
            Attendance(student_id=26, tp_course_id=12, attendance_in_percent=92.0),
            Attendance(student_id=26, tp_course_id=13, attendance_in_percent=91.0),
            Attendance(student_id=26, tp_course_id=14, attendance_in_percent=94.0),
            Attendance(student_id=26, tp_course_id=15, attendance_in_percent=89.0),
            Attendance(student_id=27, tp_course_id=11, attendance_in_percent=90.0),
            Attendance(student_id=27, tp_course_id=12, attendance_in_percent=96.0),
            Attendance(student_id=27, tp_course_id=13, attendance_in_percent=80.0),
            Attendance(student_id=27, tp_course_id=14, attendance_in_percent=85.0),
            Attendance(student_id=27, tp_course_id=15, attendance_in_percent=93.0),
            Attendance(student_id=28, tp_course_id=11, attendance_in_percent=93.0),
            Attendance(student_id=28, tp_course_id=12, attendance_in_percent=84.0),
            Attendance(student_id=28, tp_course_id=13, attendance_in_percent=95.0),
            Attendance(student_id=28, tp_course_id=14, attendance_in_percent=88.0),
            Attendance(student_id=28, tp_course_id=15, attendance_in_percent=90.0),
            Attendance(student_id=29, tp_course_id=11, attendance_in_percent=92.0),
            Attendance(student_id=29, tp_course_id=12, attendance_in_percent=87.0),
            Attendance(student_id=29, tp_course_id=13, attendance_in_percent=91.0),
            Attendance(student_id=29, tp_course_id=14, attendance_in_percent=84.0),
            Attendance(student_id=29, tp_course_id=15, attendance_in_percent=93.0),
            Attendance(student_id=30, tp_course_id=11, attendance_in_percent=95.0),
            Attendance(student_id=30, tp_course_id=12, attendance_in_percent=80.0),
            Attendance(student_id=30, tp_course_id=13, attendance_in_percent=92.0),
            Attendance(student_id=30, tp_course_id=14, attendance_in_percent=85.0),
            Attendance(student_id=30, tp_course_id=15, attendance_in_percent=91.0)
        )

        StudentsArchive.save_all(
            StudentsArchive(id=1, student_email="jdoe@conestogac.on.ca", student_first_name="John",
                            student_last_name="Doe", program_id=1, cgpa=3.52, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=2, student_email="asmith@conestogac.on.ca", student_first_name="Alice",
                            student_last_name="Smith", program_id=1, cgpa=3.86, graduation_date='2025-05-01',
                            career='Data Scientist'),
            StudentsArchive(id=3, student_email="bwilson@conestogac.on.ca", student_first_name="Brian",
                            student_last_name="Wilson", program_id=1, cgpa=3.76, graduation_date='2025-05-01',
                            career='Database Analyst'),
            StudentsArchive(id=4, student_email="slee@conestogac.on.ca", student_first_name="Sophia",
                            student_last_name="Lee", program_id=1, cgpa=3.45, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=5, student_email="mjohnson@conestogac.on.ca", student_first_name="Michael",
                            student_last_name="Johnson", program_id=1, cgpa=3.92, graduation_date='2025-05-01',
                            career='Software Engineer'),
            StudentsArchive(id=6, student_email="dwhite@conestogac.on.ca", student_first_name="David",
                            student_last_name="White", program_id=1, cgpa=3.60, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=7, student_email="elara@conestogac.on.ca", student_first_name="Emma",
                            student_last_name="Lara", program_id=1, cgpa=3.78, graduation_date='2025-05-01',
                            career='Big Data Engineer'),
            StudentsArchive(id=8, student_email="wroberts@conestogac.on.ca", student_first_name="William",
                            student_last_name="Roberts", program_id=1, cgpa=3.65, graduation_date='2025-05-01',
                            career='Database Administrator'),
            StudentsArchive(id=9, student_email="tjones@conestogac.on.ca", student_first_name="Thomas",
                            student_last_name="Jones", program_id=1, cgpa=3.88, graduation_date='2025-05-01',
                            career='Data Engineer'),
            StudentsArchive(id=10, student_email="rclark@conestogac.on.ca", student_first_name="Rachel",
                            student_last_name="Clark", program_id=1, cgpa=3.50, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=11, student_email="nmartin@conestogac.on.ca", student_first_name="Nathan",
                            student_last_name="Martin", program_id=1, cgpa=3.74, graduation_date='2025-05-01',
                            career='Business Intelligence Analyst'),
            StudentsArchive(id=12, student_email="lcarter@conestogac.on.ca", student_first_name="Lucas",
                            student_last_name="Carter", program_id=1, cgpa=3.81, graduation_date='2025-05-01',
                            career='Cloud Data Engineer'),
            StudentsArchive(id=13, student_email="kgarcia@conestogac.on.ca", student_first_name="Karen",
                            student_last_name="Garcia", program_id=1, cgpa=3.70, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=14, student_email="mthompson@conestogac.on.ca", student_first_name="Mason",
                            student_last_name="Thompson", program_id=1, cgpa=3.55, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=15, student_email="jhernandez@conestogac.on.ca", student_first_name="Jessica",
                            student_last_name="Hernandez", program_id=1, cgpa=3.89, graduation_date='2025-05-01',
                            career='Software Engineer'),
            StudentsArchive(id=16, student_email="smoore@conestogac.on.ca", student_first_name="Samuel",
                            student_last_name="Moore", program_id=1, cgpa=3.64, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=17, student_email="hbrown@conestogac.on.ca", student_first_name="Hannah",
                            student_last_name="Brown", program_id=1, cgpa=3.80, graduation_date='2025-05-01',
                            career='Data Analyst'),
            StudentsArchive(id=18, student_email="owilson@conestogac.on.ca", student_first_name="Oliver",
                            student_last_name="Wilson", program_id=1, cgpa=3.47, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=19, student_email="cphillips@conestogac.on.ca", student_first_name="Catherine",
                            student_last_name="Phillips", program_id=1, cgpa=3.91, graduation_date='2025-05-01',
                            career='Data Architect'),
            StudentsArchive(id=20, student_email="mpatel@conestogac.on.ca", student_first_name="Mohan",
                            student_last_name="Patel", program_id=1, cgpa=3.75, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=21, student_email="aevans@conestogac.on.ca", student_first_name="Amelia",
                            student_last_name="Evans", program_id=1, cgpa=3.68, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=22, student_email="bwright@conestogac.on.ca", student_first_name="Benjamin",
                            student_last_name="Wright", program_id=1, cgpa=3.72, graduation_date='2025-05-01',
                            career='ETL Developer'),
            StudentsArchive(id=23, student_email="cscott@conestogac.on.ca", student_first_name="Charlotte",
                            student_last_name="Scott", program_id=1, cgpa=3.79, graduation_date='2025-05-01',
                            career='Data Engineer'),
            StudentsArchive(id=24, student_email="ddavis@conestogac.on.ca", student_first_name="Daniel",
                            student_last_name="Davis", program_id=1, cgpa=3.83, graduation_date='2025-05-01',
                            career='Cloud Data Engineer'),
            StudentsArchive(id=25, student_email="eanderson@conestogac.on.ca", student_first_name="Ethan",
                            student_last_name="Anderson", program_id=1, cgpa=3.56, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=26, student_email="fmitchell@conestogac.on.ca", student_first_name="Faith",
                            student_last_name="Mitchell", program_id=1, cgpa=3.67, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=27, student_email="gjackson@conestogac.on.ca", student_first_name="Gabriel",
                            student_last_name="Jackson", program_id=1, cgpa=3.91, graduation_date='2025-05-01',
                            career='Software Engineer'),
            StudentsArchive(id=28, student_email="hrodriguez@conestogac.on.ca", student_first_name="Henry",
                            student_last_name="Rodriguez", program_id=1, cgpa=3.54, graduation_date='2025-05-01',
                            career='Others'),
            StudentsArchive(id=29, student_email="isanders@conestogac.on.ca", student_first_name="Isla",
                            student_last_name="Sanders", program_id=1, cgpa=3.75, graduation_date='2025-05-01',
                            career='Data Analyst'),
            StudentsArchive(id=30, student_email="jgreen@conestogac.on.ca", student_first_name="James",
                            student_last_name="Green", program_id=1, cgpa=3.85, graduation_date='2025-05-01',
                            career='Software Engineer')
        )

        StudentsGradesArchive.save_all(
            StudentsGradesArchive(id=1, archive_id=1, tp_course_id=16, grade=85.0, gpa=3.72, attendance_percent=92.5),
            StudentsGradesArchive(id=2, archive_id=1, tp_course_id=17, grade=87.0, gpa=3.33, attendance_percent=88.0),
            StudentsGradesArchive(id=3, archive_id=1, tp_course_id=18, grade=90.5, gpa=3.52, attendance_percent=91.0),
            StudentsGradesArchive(id=4, archive_id=1, tp_course_id=19, grade=88.0, gpa=3.75, attendance_percent=89.5),
            StudentsGradesArchive(id=5, archive_id=1, tp_course_id=20, grade=91.0, gpa=3.85, attendance_percent=94.0),
            StudentsGradesArchive(id=6, archive_id=2, tp_course_id=16, grade=86.0, gpa=3.70, attendance_percent=93.0),
            StudentsGradesArchive(id=7, archive_id=2, tp_course_id=17, grade=88.5, gpa=3.40, attendance_percent=89.0),
            StudentsGradesArchive(id=8, archive_id=2, tp_course_id=18, grade=89.0, gpa=3.55, attendance_percent=90.5),
            StudentsGradesArchive(id=9, archive_id=2, tp_course_id=19, grade=87.5, gpa=3.78, attendance_percent=88.5),
            StudentsGradesArchive(id=10, archive_id=2, tp_course_id=20, grade=90.5, gpa=3.80, attendance_percent=95.0),
            StudentsGradesArchive(id=11, archive_id=3, tp_course_id=16, grade=84.5, gpa=3.68, attendance_percent=92.0),
            StudentsGradesArchive(id=12, archive_id=3, tp_course_id=17, grade=86.5, gpa=3.38, attendance_percent=87.5),
            StudentsGradesArchive(id=13, archive_id=3, tp_course_id=18, grade=91.0, gpa=3.50, attendance_percent=90.0),
            StudentsGradesArchive(id=14, archive_id=3, tp_course_id=19, grade=89.5, gpa=3.74, attendance_percent=89.0),
            StudentsGradesArchive(id=15, archive_id=3, tp_course_id=20, grade=92.0, gpa=3.82, attendance_percent=94.5),
            StudentsGradesArchive(id=16, archive_id=4, tp_course_id=16, grade=85.5, gpa=3.69, attendance_percent=91.5),
            StudentsGradesArchive(id=17, archive_id=4, tp_course_id=17, grade=87.2, gpa=3.35, attendance_percent=88.2),
            StudentsGradesArchive(id=18, archive_id=4, tp_course_id=18, grade=89.8, gpa=3.54, attendance_percent=90.8),
            StudentsGradesArchive(id=19, archive_id=4, tp_course_id=19, grade=88.3, gpa=3.76, attendance_percent=89.2),
            StudentsGradesArchive(id=20, archive_id=4, tp_course_id=20, grade=90.8, gpa=3.81, attendance_percent=94.2),
            StudentsGradesArchive(id=21, archive_id=5, tp_course_id=16, grade=86.3, gpa=3.71, attendance_percent=92.8),
            StudentsGradesArchive(id=22, archive_id=5, tp_course_id=17, grade=88.0, gpa=3.39, attendance_percent=87.8),
            StudentsGradesArchive(id=23, archive_id=5, tp_course_id=18, grade=91.2, gpa=3.57, attendance_percent=91.0),
            StudentsGradesArchive(id=24, archive_id=5, tp_course_id=19, grade=89.0, gpa=3.79, attendance_percent=90.2),
            StudentsGradesArchive(id=25, archive_id=5, tp_course_id=20, grade=92.5, gpa=3.83, attendance_percent=95.0),
            StudentsGradesArchive(id=26, archive_id=6, tp_course_id=16, grade=84.8, gpa=3.67, attendance_percent=90.5),
            StudentsGradesArchive(id=27, archive_id=6, tp_course_id=17, grade=86.8, gpa=3.36, attendance_percent=86.5),
            StudentsGradesArchive(id=28, archive_id=6, tp_course_id=18, grade=90.0, gpa=3.53, attendance_percent=89.8),
            StudentsGradesArchive(id=29, archive_id=6, tp_course_id=19, grade=88.7, gpa=3.77, attendance_percent=88.9),
            StudentsGradesArchive(id=30, archive_id=6, tp_course_id=20, grade=91.5, gpa=3.79, attendance_percent=94.8),
            StudentsGradesArchive(id=31, archive_id=7, tp_course_id=16, grade=85.0, gpa=3.70, attendance_percent=91.0),
            StudentsGradesArchive(id=32, archive_id=7, tp_course_id=17, grade=87.5, gpa=3.37, attendance_percent=87.3),
            StudentsGradesArchive(id=33, archive_id=7, tp_course_id=18, grade=89.2, gpa=3.55, attendance_percent=90.2),
            StudentsGradesArchive(id=34, archive_id=7, tp_course_id=19, grade=88.0, gpa=3.75, attendance_percent=89.0),
            StudentsGradesArchive(id=35, archive_id=7, tp_course_id=20, grade=90.2, gpa=3.82, attendance_percent=94.5),
            StudentsGradesArchive(id=36, archive_id=8, tp_course_id=16, grade=86.2, gpa=3.72, attendance_percent=92.3),
            StudentsGradesArchive(id=37, archive_id=8, tp_course_id=17, grade=88.3, gpa=3.40, attendance_percent=88.5),
            StudentsGradesArchive(id=38, archive_id=8, tp_course_id=18, grade=90.5, gpa=3.56, attendance_percent=91.2),
            StudentsGradesArchive(id=39, archive_id=8, tp_course_id=19, grade=89.0, gpa=3.78, attendance_percent=90.0),
            StudentsGradesArchive(id=40, archive_id=8, tp_course_id=20, grade=92.0, gpa=3.85, attendance_percent=95.3),
            StudentsGradesArchive(id=41, archive_id=9, tp_course_id=16, grade=85.8, gpa=3.68, attendance_percent=91.8),
            StudentsGradesArchive(id=42, archive_id=9, tp_course_id=17, grade=87.0, gpa=3.34, attendance_percent=87.0),
            StudentsGradesArchive(id=43, archive_id=9, tp_course_id=18, grade=89.5, gpa=3.52, attendance_percent=90.5),
            StudentsGradesArchive(id=44, archive_id=9, tp_course_id=19, grade=88.2, gpa=3.74, attendance_percent=88.7),
            StudentsGradesArchive(id=45, archive_id=9, tp_course_id=20, grade=91.0, gpa=3.80, attendance_percent=94.1),
            StudentsGradesArchive(id=46, archive_id=10, tp_course_id=16, grade=86.5, gpa=3.73, attendance_percent=92.6),
            StudentsGradesArchive(id=47, archive_id=10, tp_course_id=17, grade=88.5, gpa=3.42, attendance_percent=89.0),
            StudentsGradesArchive(id=48, archive_id=10, tp_course_id=18, grade=90.8, gpa=3.58, attendance_percent=91.5),
            StudentsGradesArchive(id=49, archive_id=10, tp_course_id=19, grade=89.3, gpa=3.79, attendance_percent=90.8),
            StudentsGradesArchive(id=50, archive_id=10, tp_course_id=20, grade=92.3, gpa=3.87, attendance_percent=95.5),
            StudentsGradesArchive(id=51, archive_id=1, tp_course_id=21, grade=87.0, gpa=3.70, attendance_percent=93.0),
            StudentsGradesArchive(id=52, archive_id=1, tp_course_id=22, grade=89.0, gpa=3.75, attendance_percent=94.5),
            StudentsGradesArchive(id=53, archive_id=1, tp_course_id=23, grade=90.5, gpa=3.80, attendance_percent=95.0),
            StudentsGradesArchive(id=54, archive_id=1, tp_course_id=24, grade=88.0, gpa=3.72, attendance_percent=92.0),
            StudentsGradesArchive(id=55, archive_id=1, tp_course_id=25, grade=91.0, gpa=3.85, attendance_percent=96.0),
            StudentsGradesArchive(id=56, archive_id=2, tp_course_id=21, grade=85.5, gpa=3.68, attendance_percent=91.5),
            StudentsGradesArchive(id=57, archive_id=2, tp_course_id=22, grade=87.8, gpa=3.72, attendance_percent=93.0),
            StudentsGradesArchive(id=58, archive_id=2, tp_course_id=23, grade=89.2, gpa=3.78, attendance_percent=94.2),
            StudentsGradesArchive(id=59, archive_id=2, tp_course_id=24, grade=88.3, gpa=3.74, attendance_percent=92.8),
            StudentsGradesArchive(id=60, archive_id=2, tp_course_id=25, grade=90.7, gpa=3.82, attendance_percent=95.5),
            StudentsGradesArchive(id=61, archive_id=3, tp_course_id=21, grade=86.2, gpa=3.70, attendance_percent=92.5),
            StudentsGradesArchive(id=62, archive_id=3, tp_course_id=22, grade=88.0, gpa=3.74, attendance_percent=93.8),
            StudentsGradesArchive(id=63, archive_id=3, tp_course_id=23, grade=90.0, gpa=3.79, attendance_percent=95.0),
            StudentsGradesArchive(id=64, archive_id=3, tp_course_id=24, grade=87.5, gpa=3.71, attendance_percent=91.8),
            StudentsGradesArchive(id=65, archive_id=3, tp_course_id=25, grade=91.3, gpa=3.84, attendance_percent=96.2),
            StudentsGradesArchive(id=66, archive_id=4, tp_course_id=21, grade=85.8, gpa=3.67, attendance_percent=91.8),
            StudentsGradesArchive(id=67, archive_id=4, tp_course_id=22, grade=87.5, gpa=3.71, attendance_percent=92.5),
            StudentsGradesArchive(id=68, archive_id=4, tp_course_id=23, grade=89.3, gpa=3.76, attendance_percent=94.0),
            StudentsGradesArchive(id=69, archive_id=4, tp_course_id=24, grade=88.2, gpa=3.73, attendance_percent=92.3),
            StudentsGradesArchive(id=70, archive_id=4, tp_course_id=25, grade=90.9, gpa=3.81, attendance_percent=95.8),
            StudentsGradesArchive(id=71, archive_id=5, tp_course_id=21, grade=86.5, gpa=3.69, attendance_percent=92.2),
            StudentsGradesArchive(id=72, archive_id=5, tp_course_id=22, grade=88.2, gpa=3.73, attendance_percent=93.6),
            StudentsGradesArchive(id=73, archive_id=5, tp_course_id=23, grade=89.9, gpa=3.77, attendance_percent=94.5),
            StudentsGradesArchive(id=74, archive_id=5, tp_course_id=24, grade=87.8, gpa=3.72, attendance_percent=91.9),
            StudentsGradesArchive(id=75, archive_id=5, tp_course_id=25, grade=91.5, gpa=3.83, attendance_percent=96.5),
            StudentsGradesArchive(id=76, archive_id=6, tp_course_id=21, grade=86.0, gpa=3.68, attendance_percent=92.0),
            StudentsGradesArchive(id=77, archive_id=6, tp_course_id=22, grade=88.5, gpa=3.74, attendance_percent=93.5),
            StudentsGradesArchive(id=78, archive_id=6, tp_course_id=23, grade=90.2, gpa=3.79, attendance_percent=94.8),
            StudentsGradesArchive(id=79, archive_id=6, tp_course_id=24, grade=87.9, gpa=3.72, attendance_percent=92.5),
            StudentsGradesArchive(id=80, archive_id=6, tp_course_id=25, grade=91.1, gpa=3.81, attendance_percent=96.0),
            StudentsGradesArchive(id=81, archive_id=7, tp_course_id=21, grade=85.7, gpa=3.66, attendance_percent=91.5),
            StudentsGradesArchive(id=82, archive_id=7, tp_course_id=22, grade=87.3, gpa=3.70, attendance_percent=92.8),
            StudentsGradesArchive(id=83, archive_id=7, tp_course_id=23, grade=89.5, gpa=3.75, attendance_percent=94.3),
            StudentsGradesArchive(id=84, archive_id=7, tp_course_id=24, grade=88.1, gpa=3.71, attendance_percent=92.0),
            StudentsGradesArchive(id=85, archive_id=7, tp_course_id=25, grade=90.8, gpa=3.80, attendance_percent=95.6),
            StudentsGradesArchive(id=86, archive_id=8, tp_course_id=21, grade=86.4, gpa=3.69, attendance_percent=92.3),
            StudentsGradesArchive(id=87, archive_id=8, tp_course_id=22, grade=88.1, gpa=3.73, attendance_percent=93.7),
            StudentsGradesArchive(id=88, archive_id=8, tp_course_id=23, grade=89.7, gpa=3.76, attendance_percent=94.6),
            StudentsGradesArchive(id=89, archive_id=8, tp_course_id=24, grade=87.6, gpa=3.70, attendance_percent=91.7),
            StudentsGradesArchive(id=90, archive_id=8, tp_course_id=25, grade=91.4, gpa=3.82, attendance_percent=96.3),
            StudentsGradesArchive(id=91, archive_id=9, tp_course_id=21, grade=85.9, gpa=3.67, attendance_percent=91.7),
            StudentsGradesArchive(id=92, archive_id=9, tp_course_id=22, grade=87.6, gpa=3.71, attendance_percent=92.9),
            StudentsGradesArchive(id=93, archive_id=9, tp_course_id=23, grade=89.4, gpa=3.74, attendance_percent=94.1),
            StudentsGradesArchive(id=94, archive_id=9, tp_course_id=24, grade=88.0, gpa=3.72, attendance_percent=92.4),
            StudentsGradesArchive(id=95, archive_id=9, tp_course_id=25, grade=90.9, gpa=3.81, attendance_percent=95.9),
            StudentsGradesArchive(id=96, archive_id=10, tp_course_id=21, grade=86.2, gpa=3.68, attendance_percent=92.1),
            StudentsGradesArchive(id=97, archive_id=10, tp_course_id=22, grade=88.3, gpa=3.73, attendance_percent=93.4),
            StudentsGradesArchive(id=98, archive_id=10, tp_course_id=23, grade=90.1, gpa=3.78, attendance_percent=94.9),
            StudentsGradesArchive(id=99, archive_id=10, tp_course_id=24, grade=87.7, gpa=3.71, attendance_percent=91.8),
            StudentsGradesArchive(id=100, archive_id=10, tp_course_id=25, grade=91.2, gpa=3.83, attendance_percent=96.4),
            StudentsGradesArchive(id=101, archive_id=11, tp_course_id=21, grade=85.4, gpa=3.68, attendance_percent=91.2),
            StudentsGradesArchive(id=102, archive_id=11, tp_course_id=22, grade=87.6, gpa=3.74, attendance_percent=92.8),
            StudentsGradesArchive(id=103, archive_id=11, tp_course_id=23, grade=89.1, gpa=3.79, attendance_percent=94.5),
            StudentsGradesArchive(id=104, archive_id=11, tp_course_id=24, grade=86.8, gpa=3.71, attendance_percent=90.9),
            StudentsGradesArchive(id=105, archive_id=11, tp_course_id=25, grade=90.2, gpa=3.83, attendance_percent=96.0),
            StudentsGradesArchive(id=106, archive_id=12, tp_course_id=21, grade=86.0, gpa=3.70, attendance_percent=92.0),
            StudentsGradesArchive(id=107, archive_id=12, tp_course_id=22, grade=88.3, gpa=3.75, attendance_percent=93.4),
            StudentsGradesArchive(id=108, archive_id=12, tp_course_id=23, grade=90.6, gpa=3.81, attendance_percent=95.3),
            StudentsGradesArchive(id=109, archive_id=12, tp_course_id=24, grade=87.9, gpa=3.73, attendance_percent=91.5),
            StudentsGradesArchive(id=110, archive_id=12, tp_course_id=25, grade=91.5, gpa=3.85, attendance_percent=96.7),
            StudentsGradesArchive(id=111, archive_id=13, tp_course_id=21, grade=85.2, gpa=3.67, attendance_percent=90.8),
            StudentsGradesArchive(id=112, archive_id=13, tp_course_id=22, grade=87.8, gpa=3.73, attendance_percent=92.9),
            StudentsGradesArchive(id=113, archive_id=13, tp_course_id=23, grade=89.7, gpa=3.78, attendance_percent=94.1),
            StudentsGradesArchive(id=114, archive_id=13, tp_course_id=24, grade=86.5, gpa=3.70, attendance_percent=91.2),
            StudentsGradesArchive(id=115, archive_id=13, tp_course_id=25, grade=90.8, gpa=3.82, attendance_percent=95.6),
            StudentsGradesArchive(id=116, archive_id=14, tp_course_id=21, grade=85.9, gpa=3.69, attendance_percent=91.5),
            StudentsGradesArchive(id=117, archive_id=14, tp_course_id=22, grade=88.1, gpa=3.74, attendance_percent=93.2),
            StudentsGradesArchive(id=118, archive_id=14, tp_course_id=23, grade=90.2, gpa=3.80, attendance_percent=95.0),
            StudentsGradesArchive(id=119, archive_id=14, tp_course_id=24, grade=87.7, gpa=3.72, attendance_percent=92.1),
            StudentsGradesArchive(id=120, archive_id=14, tp_course_id=25, grade=91.2, gpa=3.84, attendance_percent=96.3),
            StudentsGradesArchive(id=121, archive_id=15, tp_course_id=21, grade=85.6, gpa=3.68, attendance_percent=91.0),
            StudentsGradesArchive(id=122, archive_id=15, tp_course_id=22, grade=87.9, gpa=3.74, attendance_percent=92.7),
            StudentsGradesArchive(id=123, archive_id=15, tp_course_id=23, grade=89.9, gpa=3.79, attendance_percent=94.2),
            StudentsGradesArchive(id=124, archive_id=15, tp_course_id=24, grade=86.6, gpa=3.71, attendance_percent=90.8),
            StudentsGradesArchive(id=125, archive_id=15, tp_course_id=25, grade=90.5, gpa=3.83, attendance_percent=95.9),
            StudentsGradesArchive(id=126, archive_id=16, tp_course_id=21, grade=85.3, gpa=3.67, attendance_percent=90.7),
            StudentsGradesArchive(id=127, archive_id=16, tp_course_id=22, grade=87.5, gpa=3.72, attendance_percent=92.6),
            StudentsGradesArchive(id=128, archive_id=16, tp_course_id=23, grade=89.2, gpa=3.77, attendance_percent=93.8),
            StudentsGradesArchive(id=129, archive_id=16, tp_course_id=24, grade=86.9, gpa=3.71, attendance_percent=91.4),
            StudentsGradesArchive(id=130, archive_id=16, tp_course_id=25, grade=90.3, gpa=3.82, attendance_percent=95.7),
            StudentsGradesArchive(id=131, archive_id=17, tp_course_id=21, grade=85.8, gpa=3.69, attendance_percent=91.2),
            StudentsGradesArchive(id=132, archive_id=17, tp_course_id=22, grade=88.0, gpa=3.74, attendance_percent=93.1),
            StudentsGradesArchive(id=133, archive_id=17, tp_course_id=23, grade=90.4, gpa=3.79, attendance_percent=94.9),
            StudentsGradesArchive(id=134, archive_id=17, tp_course_id=24, grade=87.5, gpa=3.72, attendance_percent=91.8),
            StudentsGradesArchive(id=135, archive_id=17, tp_course_id=25, grade=91.1, gpa=3.84, attendance_percent=96.2),
            StudentsGradesArchive(id=136, archive_id=18, tp_course_id=21, grade=85.5, gpa=3.68, attendance_percent=91.0),
            StudentsGradesArchive(id=137, archive_id=18, tp_course_id=22, grade=87.7, gpa=3.73, attendance_percent=92.8),
            StudentsGradesArchive(id=138, archive_id=18, tp_course_id=23, grade=89.6, gpa=3.78, attendance_percent=94.0),
            StudentsGradesArchive(id=139, archive_id=18, tp_course_id=24, grade=86.4, gpa=3.70, attendance_percent=90.9),
            StudentsGradesArchive(id=140, archive_id=18, tp_course_id=25, grade=90.7, gpa=3.81, attendance_percent=95.5),
            StudentsGradesArchive(id=141, archive_id=19, tp_course_id=21, grade=85.9, gpa=3.69, attendance_percent=91.3),
            StudentsGradesArchive(id=142, archive_id=19, tp_course_id=22, grade=88.2, gpa=3.75, attendance_percent=93.3),
            StudentsGradesArchive(id=143, archive_id=19, tp_course_id=23, grade=90.5, gpa=3.80, attendance_percent=95.1),
            StudentsGradesArchive(id=144, archive_id=19, tp_course_id=24, grade=87.8, gpa=3.73, attendance_percent=92.2),
            StudentsGradesArchive(id=145, archive_id=19, tp_course_id=25, grade=91.4, gpa=3.85, attendance_percent=96.4),
            StudentsGradesArchive(id=146, archive_id=20, tp_course_id=21, grade=85.4, gpa=3.67, attendance_percent=90.9),
            StudentsGradesArchive(id=147, archive_id=20, tp_course_id=22, grade=87.6, gpa=3.72, attendance_percent=92.7),
            StudentsGradesArchive(id=148, archive_id=20, tp_course_id=23, grade=89.8, gpa=3.78, attendance_percent=94.3),
            StudentsGradesArchive(id=149, archive_id=20, tp_course_id=24, grade=86.7, gpa=3.71, attendance_percent=91.1),
            StudentsGradesArchive(id=150, archive_id=20, tp_course_id=25, grade=90.9, gpa=3.83, attendance_percent=95.8),
            StudentsGradesArchive(id=151, archive_id=21, tp_course_id=21, grade=85.1, gpa=3.66, attendance_percent=90.6),
            StudentsGradesArchive(id=152, archive_id=21, tp_course_id=22, grade=87.3, gpa=3.71, attendance_percent=92.5),
            StudentsGradesArchive(id=153, archive_id=21, tp_course_id=23, grade=89.5, gpa=3.76, attendance_percent=93.7),
            StudentsGradesArchive(id=154, archive_id=21, tp_course_id=24, grade=86.2, gpa=3.69, attendance_percent=90.5),
            StudentsGradesArchive(id=155, archive_id=21, tp_course_id=25, grade=90.6, gpa=3.80, attendance_percent=95.4),
            StudentsGradesArchive(id=156, archive_id=22, tp_course_id=21, grade=85.7, gpa=3.69, attendance_percent=91.1),
            StudentsGradesArchive(id=157, archive_id=22, tp_course_id=22, grade=88.1, gpa=3.74, attendance_percent=93.0),
            StudentsGradesArchive(id=158, archive_id=22, tp_course_id=23, grade=90.3, gpa=3.79, attendance_percent=94.8),
            StudentsGradesArchive(id=159, archive_id=22, tp_course_id=24, grade=87.6, gpa=3.72, attendance_percent=91.7),
            StudentsGradesArchive(id=160, archive_id=22, tp_course_id=25, grade=91.0, gpa=3.84, attendance_percent=96.1),
            StudentsGradesArchive(id=161, archive_id=23, tp_course_id=21, grade=85.2, gpa=3.67, attendance_percent=90.8),
            StudentsGradesArchive(id=162, archive_id=23, tp_course_id=22, grade=87.5, gpa=3.72, attendance_percent=92.6),
            StudentsGradesArchive(id=163, archive_id=23, tp_course_id=23, grade=89.9, gpa=3.77, attendance_percent=94.1),
            StudentsGradesArchive(id=164, archive_id=23, tp_course_id=24, grade=86.5, gpa=3.70, attendance_percent=91.0),
            StudentsGradesArchive(id=165, archive_id=23, tp_course_id=25, grade=90.8, gpa=3.82, attendance_percent=95.6),
            StudentsGradesArchive(id=166, archive_id=24, tp_course_id=21, grade=85.6, gpa=3.68, attendance_percent=91.0),
            StudentsGradesArchive(id=167, archive_id=24, tp_course_id=22, grade=88.0, gpa=3.74, attendance_percent=93.1),
            StudentsGradesArchive(id=168, archive_id=24, tp_course_id=23, grade=90.4, gpa=3.79, attendance_percent=94.9),
            StudentsGradesArchive(id=169, archive_id=24, tp_course_id=24, grade=87.4, gpa=3.72, attendance_percent=91.6),
            StudentsGradesArchive(id=170, archive_id=24, tp_course_id=25, grade=91.3, gpa=3.85, attendance_percent=96.3),
            StudentsGradesArchive(id=171, archive_id=25, tp_course_id=21, grade=85.9, gpa=3.69, attendance_percent=91.3),
            StudentsGradesArchive(id=172, archive_id=25, tp_course_id=22, grade=88.3, gpa=3.75, attendance_percent=93.4),
            StudentsGradesArchive(id=173, archive_id=25, tp_course_id=23, grade=90.6, gpa=3.81, attendance_percent=95.2),
            StudentsGradesArchive(id=174, archive_id=25, tp_course_id=24, grade=87.9, gpa=3.73, attendance_percent=92.3),
            StudentsGradesArchive(id=175, archive_id=25, tp_course_id=25, grade=91.5, gpa=3.86, attendance_percent=96.5),
            StudentsGradesArchive(id=176, archive_id=26, tp_course_id=21, grade=85.3, gpa=3.68, attendance_percent=91.1),
            StudentsGradesArchive(id=177, archive_id=26, tp_course_id=22, grade=87.9, gpa=3.74, attendance_percent=92.9),
            StudentsGradesArchive(id=178, archive_id=26, tp_course_id=23, grade=90.1, gpa=3.79, attendance_percent=94.4),
            StudentsGradesArchive(id=179, archive_id=26, tp_course_id=24, grade=86.8, gpa=3.71, attendance_percent=91.3),
            StudentsGradesArchive(id=180, archive_id=26, tp_course_id=25, grade=91.0, gpa=3.83, attendance_percent=95.7),
            StudentsGradesArchive(id=181, archive_id=27, tp_course_id=21, grade=85.6, gpa=3.69, attendance_percent=90.9),
            StudentsGradesArchive(id=182, archive_id=27, tp_course_id=22, grade=87.2, gpa=3.73, attendance_percent=92.4),
            StudentsGradesArchive(id=183, archive_id=27, tp_course_id=23, grade=89.7, gpa=3.78, attendance_percent=94.1),
            StudentsGradesArchive(id=184, archive_id=27, tp_course_id=24, grade=86.1, gpa=3.70, attendance_percent=91.6),
            StudentsGradesArchive(id=185, archive_id=27, tp_course_id=25, grade=90.5, gpa=3.82, attendance_percent=95.3),
            StudentsGradesArchive(id=186, archive_id=28, tp_course_id=21, grade=85.0, gpa=3.66, attendance_percent=90.8),
            StudentsGradesArchive(id=187, archive_id=28, tp_course_id=22, grade=87.4, gpa=3.71, attendance_percent=92.3),
            StudentsGradesArchive(id=188, archive_id=28, tp_course_id=23, grade=89.9, gpa=3.77, attendance_percent=93.9),
            StudentsGradesArchive(id=189, archive_id=28, tp_course_id=24, grade=86.7, gpa=3.70, attendance_percent=91.4),
            StudentsGradesArchive(id=190, archive_id=28, tp_course_id=25, grade=90.8, gpa=3.83, attendance_percent=95.6),
            StudentsGradesArchive(id=191, archive_id=29, tp_course_id=21, grade=85.5, gpa=3.68, attendance_percent=91.0),
            StudentsGradesArchive(id=192, archive_id=29, tp_course_id=22, grade=87.8, gpa=3.73, attendance_percent=92.7),
            StudentsGradesArchive(id=193, archive_id=29, tp_course_id=23, grade=90.2, gpa=3.79, attendance_percent=94.5),
            StudentsGradesArchive(id=194, archive_id=29, tp_course_id=24, grade=86.9, gpa=3.71, attendance_percent=91.5),
            StudentsGradesArchive(id=195, archive_id=29, tp_course_id=25, grade=91.2, gpa=3.84, attendance_percent=96.0),
            StudentsGradesArchive(id=196, archive_id=30, tp_course_id=21, grade=85.7, gpa=3.70, attendance_percent=91.2),
            StudentsGradesArchive(id=197, archive_id=30, tp_course_id=22, grade=87.1, gpa=3.72, attendance_percent=92.2),
            StudentsGradesArchive(id=198, archive_id=30, tp_course_id=23, grade=90.0, gpa=3.77, attendance_percent=94.2),
            StudentsGradesArchive(id=199, archive_id=30, tp_course_id=24, grade=86.3, gpa=3.69, attendance_percent=91.0),
            StudentsGradesArchive(id=200, archive_id=30, tp_course_id=25, grade=91.4, gpa=3.85, attendance_percent=96.1)
        )
    pass
